version: '3'

services:
  web:
    build: .
    command: /bin/sh -c "/start.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - nginx_network
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge




