# Generated by Django 4.2 on 2023-10-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.CharField(max_length=120)),
                (
                    "part_number_new",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("part_number_description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="product_image/")),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("updated", "Updated"), ("active", "Active")],
                        default="active",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
