# Generated by Django 4.2 on 2023-10-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_productprices_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=300)),
            ],
        ),
    ]
