# Generated by Django 4.2 on 2023-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_searchhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
