# Generated by Django 4.2 on 2023-10-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productprices",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=100, null=True
            ),
        ),
    ]
