# Generated by Django 4.1 on 2023-10-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_productprices_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="part_number",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
